version = 1

[[issues]]
id = "VET-V0010"
paths = ["**/*.go"]

[[issues]]
id = "GO-W6007"
paths = ["**/*.go"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/flowline-io/flowbot"

[[analyzers]]
name = "shell"
