linters-settings:
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting # https://github.com/go-critic/go-critic/issues/755

linters:
  enable-all: true
  disable:
    - errcheck
    - prealloc
    - gosec
    - gochecknoglobals

# options for analysis running
run:
  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - mysql
    - rethinkdb
    - mongodb
