version: "3"
tasks:
  default:
    desc: Default task - run common checks
    cmds:
      - task: tidy
      - task: swagger
      - task: format
      - task: lint
      - task: scc
      - echo "All checks completed"

  check:
    desc: Run all security and quality checks
    cmds:
      - task: lint
      - task: secure
      - task: leak
      - task: gosec
      - echo "All checks completed"

  # Build tasks
  build:
    desc: Build flowbot server
    cmds:
      - GOEXPERIMENT=goroutineleakprofile go build -v -o bin/flowbot ./cmd

  build:agent:
    desc: Build flowbot agent
    cmds:
      - go build -v -o bin/flowbot-agent ./cmd/agent

  build:composer:
    desc: Build composer tool
    cmds:
      - go build -v -o bin/composer ./cmd/composer

  build:app:wasm:
    desc: Build admin PWA WebAssembly binary
    env:
      GOOS: js
      GOARCH: wasm
      CGO_ENABLED: "0"
    cmds:
      - go build -v -o web/app.wasm ./cmd/app

  build:app:
    desc: Build admin PWA (WebAssembly + server)
    cmds:
      - task: build:app:wasm
      - go build -v -o bin/flowbot-app ./cmd/app

  build:all:
    desc: Build all binaries
    cmds:
      - task: build
      - task: build:agent
      - task: build:composer
      - task: build:app

  # Run tasks
  run:
    desc: Run flowbot server
    cmds:
      - go run -tags swagger ./cmd

  run:agent:
    desc: Run flowbot agent
    cmds:
      - go run ./cmd/agent

  run:app:
    desc: Run admin PWA server
    cmds:
      - task: build:app:wasm
      - go run ./cmd/app

  # Code quality tasks
  cloc:
    desc: Count lines of code using cloc
    cmds:
      - cloc --exclude-dir=node_modules --exclude-ext=json .

  scc:
    desc: Generate code statistics using scc
    cmds:
      - go tool scc > ./cloc/{{ now.Format "2006-01-02" }}.txt

  lint:
    desc: Run static code analysis
    cmds:
      - go tool revive -config revive.toml -formatter friendly ./...
      - task: lint:action

  lint:action:
    desc: Lint GitHub Actions workflow files
    cmds:
      - go tool actionlint

  format:
    desc: Format code (Go and other files)
    cmds:
      - go fmt ./...
      - npx prettier --write .

  tidy:
    desc: Clean up Go module dependencies
    cmds:
      - go mod tidy

  # Security tasks
  secure:
    desc: Check for Go vulnerabilities
    cmds:
      - go tool govulncheck ./...

  leak:
    desc: Find secrets with Gitleaks
    cmds:
      - go tool gitleaks git -v

  gosec:
    desc: Run Go security checker
    cmds:
      - go tool gosec ./...

  # Test tasks
  test:
    desc: Run tests in pkg/utils package
    cmds:
      - go test ./pkg/utils/... -v

  test:all:
    desc: Run all tests
    cmds:
      - go test ./... -v

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test ./... -coverprofile=coverage.out -covermode=atomic
      - go tool cover -html=coverage.out -o coverage.html
      - echo "coverage report generated in coverage.html"

  # Documentation tasks
  swagger:
    desc: Generate Swagger API documentation
    cmds:
      - go tool swag init -g cmd/main.go -o ./docs/api
      - go tool swag fmt -g cmd/main.go

  doc:
    desc: Generate database schema documentation
    cmds:
      - go run ./cmd/composer doc

  # Code generation tasks
  dao:
    desc: Generate DAO code from database
    cmds:
      - go run ./cmd/composer dao

  generator:bot:
    desc: Generate bot code (task generator:bot NAME=botname RULE=command,form)
    cmds:
      - go run ./cmd/composer generator bot -name {{.NAME | default "example"}} -rule {{.RULE | default "command"}}

  generator:vendor:
    desc: Generate vendor API code (task generator:vendor NAME=vendorname)
    cmds:
      - go run ./cmd/composer generator vendor -name {{.NAME | default "example"}}

  # Database migration tasks
  migrate:
    desc: Import database migrations
    cmds:
      - go run ./cmd/composer migrate import

  migration:
    desc: Create new migration file (task migration NAME=migration_name)
    cmds:
      - go run ./cmd/composer migrate migration -name {{.NAME | default .CLI_ARGS | default "migration"}}

  # Workflow tasks
  workflow:import:
    desc: Import workflow configuration (task workflow:import TOKEN=xxx PATH=./path/to/workflow.yaml)
    cmds:
      - go run ./cmd/composer workflow import -token {{.TOKEN}} -path {{.PATH}}

  # Development tools
  tools:
    desc: Install all development tools
    cmds:
      - go mod download
      - npm install -g prettier

  # Release tasks
  snapshot:
    desc: Create snapshot release
    cmds:
      - go tool goreleaser release --snapshot --clean

  # Utility tasks
  clean:
    desc: Clean build artifacts and temporary files
    cmds:
      - go clean -cache -testcache
      - cmd: rm -rf bin/ tmp/ coverage.out coverage.html
        ignore_error: true

  air:
    desc: Run with live reload using air
    cmds:
      - air -c .air.toml
