// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthentication = "authentications"

// Authentication mapped from table <authentications>
type Authentication struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          string     `gorm:"column:uid;not null" json:"uid"`
	Topic        string     `gorm:"column:topic;not null" json:"topic"`
	ConnectionID *int64     `gorm:"column:connection_id" json:"connection_id"`
	Name         string     `gorm:"column:name;not null" json:"name"`
	Type         string     `gorm:"column:type;not null" json:"type"`
	Credentials  JSON       `gorm:"column:credentials;not null" json:"credentials"`
	ExpiresAt    *time.Time `gorm:"column:expires_at" json:"expires_at"`
	Enabled      bool       `gorm:"column:enabled;not null;default:1" json:"enabled"`
	CreatedAt    time.Time  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Authentication's table name
func (*Authentication) TableName() string {
	return TableNameAuthentication
}
