// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePage = "chatbot_page"

// Page mapped from table <chatbot_page>
type Page struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PageID    string    `gorm:"column:page_id;not null" json:"page_id"`
	UID       string    `gorm:"column:uid;not null" json:"uid"`
	Topic     string    `gorm:"column:topic;not null" json:"topic"`
	Type      PageType  `gorm:"column:type;not null" json:"type"`
	Schema    JSON      `gorm:"column:schema;not null" json:"schema"`
	State     PageState `gorm:"column:state;not null" json:"state"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Page's table name
func (*Page) TableName() string {
	return TableNamePage
}
