// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUrl = "chatbot_url"

// Url mapped from table <chatbot_url>
type Url struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Flag      string    `gorm:"column:flag;not null" json:"flag"`
	URL       string    `gorm:"column:url;not null" json:"url"`
	State     UrlState  `gorm:"column:state;not null" json:"state"`
	ViewCount int32     `gorm:"column:view_count;not null" json:"view_count"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Url's table name
func (*Url) TableName() string {
	return TableNameUrl
}
