// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameParameter = "chatbot_parameter"

// Parameter mapped from table <chatbot_parameter>
type Parameter struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Flag      string    `gorm:"column:flag;not null" json:"flag"`
	Params    JSON      `gorm:"column:params" json:"params"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	ExpiredAt time.Time `gorm:"column:expired_at;not null" json:"expired_at"`
}

// TableName Parameter's table name
func (*Parameter) TableName() string {
	return TableNameParameter
}
