// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInstruct = "chatbot_instruct"

// Instruct mapped from table <chatbot_instruct>
type Instruct struct {
	ID        int32            `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	No        string           `gorm:"column:no;not null" json:"no"`
	UID       string           `gorm:"column:uid;not null" json:"uid"`
	Object    InstructObject   `gorm:"column:object;not null" json:"object"`
	Bot       string           `gorm:"column:bot;not null" json:"bot"`
	Flag      string           `gorm:"column:flag;not null" json:"flag"`
	Content   JSON             `gorm:"column:content;not null" json:"content"`
	Priority  InstructPriority `gorm:"column:priority;not null" json:"priority"`
	State     InstructState    `gorm:"column:state;not null" json:"state"`
	ExpireAt  time.Time        `gorm:"column:expire_at;not null" json:"expire_at"`
	CreatedAt time.Time        `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time        `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Instruct's table name
func (*Instruct) TableName() string {
	return TableNameInstruct
}
