id: chain_call_rest_api
name: test rule chain
root: true
debugMode: true

nodes:
  - id: s1
    type: jsFilter
    name: filter
    configuration:
      jsScript: return msg.deviceId=='aa';

  - id: s2
    type: jsTransform
    name: transform
    configuration:
      jsScript: msg.temperature=msg.temperature/10; return {'msg':msg,'metadata':metadata,'msgType':msgType};

  - id: s3
    type: log
    name: logging
    configuration:
      jsScript: return '\nIncoming message:\n' + JSON.stringify(msg) + '\nIncoming metadata:\n' + JSON.stringify(metadata);

pipelines:
  - s1 --True--> s2 --Success--> s3
