package devops

const (
	OpHealth                  = "health"
	OpStatus                  = "status"
	OpBeszelListSystems       = "beszel_list_systems"
	OpBeszelGetSystem         = "beszel_get_system"
	OpUptimekumaHealth        = "uptimekuma_health"
	OpUptimekumaMetrics       = "uptimekuma_metrics"
	OpTraefikOverview         = "traefik_overview"
	OpTraefikListRouters      = "traefik_list_routers"
	OpTraefikListServices     = "traefik_list_services"
	OpGrafanaHealth           = "grafana_health"
	OpGrafanaListDatasources  = "grafana_list_datasources"
	OpGrafanaSearchDashboards = "grafana_search_dashboards"
	OpGrafanaQuery            = "grafana_query"
	OpWakapiHealth            = "wakapi_health"
	OpWakapiSummary           = "wakapi_summary"
	OpWakapiListProjects      = "wakapi_list_projects"
	OpWakapiAllTime           = "wakapi_all_time"
	OpDozzleHealth            = "dozzle_health"
	OpNetalertxHealth         = "netalertx_health"
	OpNetalertxListDevices    = "netalertx_list_devices"
	OpNetalertxTotals         = "netalertx_totals"
	OpNetalertxSearchDevices  = "netalertx_search_devices"
	OpScanopyHealth           = "scanopy_health"
	OpScanopyVersion          = "scanopy_version"
	OpScanopyListNetworks     = "scanopy_list_networks"
	OpScanopyListHosts        = "scanopy_list_hosts"
	OpScanopyGetHost          = "scanopy_get_host"
	OpScanopyListServices     = "scanopy_list_services"
	OpScanopyListDaemons      = "scanopy_list_daemons"
)
