version: '3.7'

services:
  tinode:
    image: ghcr.io/sysatom/tinode:latest
    restart: always
    volumes:
      - ./tinode.conf:/opt/app/tinode.conf
    ports:
      - "6060:6060"
      - "16060:16060"
      - "12000:12000"
      - "12001:12001"
      - "12002:12002"
      - "12003:12003"
    environment:
      "TINODE_URL": ${TINODE_URL}
