---
log_level: debug
bots_enabled:
  - "dev"
  - "clipboard"
  - "url"
  - "anki"
api:
  url: "http://127.0.0.1:6060"
  token: ""
updater:
  github_token: ""
script_engine:
  enabled: false
  script_path: "./scripts"
  uid: ""
  gid: ""
  skip_watch_dir:
    - ".git"
    - ".vscode"
