basePath: /
definitions:
  types.ServerComMessage:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:6060
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /bot/dev/v1/example:
    get:
      consumes:
      - application/json
      description: get example data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ServerComMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.ServerComMessage'
      summary: Show example
      tags:
      - dev
swagger: "2.0"
