basePath: /bot
definitions:
  protocol.Response:
    properties:
      data:
        description: Response data
      message:
        description: |-
          Error message, it is recommended to fill in a human-readable error message when the action fails to execute,
          or an empty string when it succeeds.
        type: string
      retcode:
        description: The return code, which must conform to the return code rules
          defined later on this page
        type: integer
      status:
        allOf:
        - $ref: '#/definitions/protocol.ResponseStatus'
        description: |-
          Execution status (success or failure), must be one of ok and failed,
          indicating successful and unsuccessful execution, respectively.
    type: object
  protocol.ResponseStatus:
    enum:
    - ok
    - failed
    type: string
    x-enum-varnames:
    - Success
    - Failed
host: localhost:6060
info:
  contact:
    email: dev@tsundata.com
    name: API Support
  description: Flowbot Chatbot API
  license:
    name: GPL 3.0
    url: https://github.com/flowline-io/flowbot/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Flowbot API
  version: "1.0"
paths:
  /dev/v1/example:
    get:
      consumes:
      - application/json
      description: get example data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/protocol.Response'
      summary: Show example
      tags:
      - dev
swagger: "2.0"
