---
name: example
describe: do something...

triggers:
  - type: manual # cron, manual, webhook
  - type: cron
    rule:
      spec: '* * * * *' # if cron
  - type: webhook

pipeline:
  - input -> add_two_number -> out1
  - add_two_number -> out2


tasks:
  - id: input
    action: in@dev
    describe: do something... # optional
    params: # optional
      param1: val1
      param2: val2
    vars: # optional
      - var1
      - var2
    conn: # optional
      - conn1
      - conn2

  - id: add_two_number
    action: add@dev

  - id: out1
    action: out@dev

  - id: out2
    action: out@dev

