// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TriggerCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flowbot-surface card-body p-3 cursor-pointer\" :class=\"getTriggerErrorClass(idx)\" @click=\"selectNode('trigger', idx)\" data-testid=\"trigger-card\"><div class=\"flex flex-row items-center justify-between\"><div class=\"flex items-center gap-3\"><div class=\"w-8 h-8 rounded bg-primary/10 flex items-center justify-center text-primary text-sm font-bold\"><span x-show=\"t.type === 'event'\">E</span> <span x-show=\"t.type === 'webhook'\">W</span> <span x-show=\"t.type === 'cron'\">C</span></div><div><div class=\"text-sm font-medium text-base-content\" x-text=\"'Event: ' + (t.event || '...')\" x-show=\"t.type === 'event'\"></div><div class=\"text-sm font-medium text-base-content\" x-text=\"'Webhook: ' + ((t.webhook && t.webhook.path) || '...')\" x-show=\"t.type === 'webhook'\"></div><div class=\"text-sm font-medium text-base-content\" x-text=\"'Cron: ' + (t.cron || '...')\" x-show=\"t.type === 'cron'\"></div></div></div><div class=\"flex items-center gap-2\"><label class=\"relative inline-flex items-center cursor-pointer\" @click.stop><input type=\"checkbox\" x-model=\"t.enabled\" @change=\"onTriggerEnabledChange()\" class=\"sr-only peer\" data-testid=\"trigger-switch\"><div class=\"w-9 h-5 bg-base-300 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:bg-primary after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:rounded-full after:h-4 after:w-4 after:transition-all\"></div></label> <button type=\"button\" @click.stop=\"confirmRemoveTrigger(idx)\" class=\"text-base-content/30 hover:text-error\" data-testid=\"btn-remove-trigger\">&times;</button></div></div><template x-for=\"(msg, msgIdx) in getNodeErrorMessages('trigger', idx)\" :key=\"msgIdx\"><p class=\"text-xs text-error mt-2\" data-testid=\"trigger-error-message\" x-text=\"msg\"></p></template></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func StepCard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flowbot-surface card-body p-4 relative group cursor-pointer\" :class=\"getStepErrorClass(idx)\" draggable=\"true\" :data-sort-idx=\"idx\" @dragstart=\"onStepDragStart(idx, $event)\" @dragend=\"onStepDragEnd($event)\" @dragover=\"onStepDragOver(idx, $event)\" @dragleave=\"onStepDragLeave($event)\" @drop=\"onStepDrop(idx, $event)\" @click=\"selectNode('step', idx)\" data-testid=\"step-card\"><div class=\"absolute -top-2 right-2 hidden group-hover:flex gap-1 bg-base-100 border rounded-box shadow-sm px-2 py-0.5 text-xs\"><button type=\"button\" @click.stop=\"duplicateStep(idx)\" class=\"text-base-content/30 hover:text-base-content\" data-testid=\"btn-copy-step\">Copy</button> <button type=\"button\" @click.stop=\"confirmRemoveStep(idx)\" class=\"text-error/50 hover:text-error\" data-testid=\"btn-delete-step\">Delete</button></div><div class=\"flex items-center gap-3\"><div class=\"w-8 h-8 rounded bg-base-200 flex items-center justify-center text-base-content/50 text-xs font-bold\" x-text=\"(step.capability || '?')[0].toUpperCase()\"></div><div class=\"flex-1 min-w-0\"><div class=\"text-sm font-medium text-base-content truncate\" x-text=\"step.name || 'Unnamed Step'\"></div><div class=\"text-xs text-base-content/30 truncate\" x-text=\"step.capability + '.' + step.operation\"></div></div><button type=\"button\" @click.stop=\"selectNode('step', idx)\" class=\"text-base-content/30 hover:text-base-content\">...</button></div><div x-show=\"step.paramsText && step.paramsText.trim() !== '{}'\" class=\"mt-2 text-xs text-base-content/50 font-mono bg-base-200 rounded-box p-2 whitespace-pre-wrap break-words\" x-text=\"formatStepParamsPreview(step.paramsText)\"></div><template x-for=\"(msg, msgIdx) in getNodeErrorMessages('step', idx)\" :key=\"msgIdx\"><p class=\"text-xs text-error mt-2\" data-testid=\"step-error-message\" x-text=\"msg\"></p></template></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
